"""The ONE place a DDD spec is loaded from disk.

A narrative has two owners and therefore two files:

  ``<slug>.recipe.yaml``          git-owned. How to film it: selectors, URLs,
                                  viewports, actions, pacing, and the local
                                  falsifiable ``concept_claim``. This is code —
                                  it is coupled to the app and belongs in the PR
                                  that changes the app.
  ``<slug>.narrative.lock.json``  generated by ``narrative pull``, committed,
                                  NEVER hand-edited. A read-through cache of the
                                  cloud-owned story at a pinned version.

``compose`` joins them on the stable scene ``id`` (L0) and returns the same raw
spec dict every consumer has always parsed, so ``UnifiedSpec`` is unchanged.

Legacy single-file ``<slug>.yaml`` specs still load, unchanged, so this module
can be adopted call-site by call-site before anything is migrated.

Why one loader at all: before this module, eleven call sites across ``scripts/``
each did their own ``yaml.safe_load`` of a spec path. Changing the on-disk shape
is impossible until exactly one thing reads it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

from scripts.ddd.schemas.models import UnifiedSpec


class SpecCompositionError(Exception):
    """A recipe and a narrative lock that do not describe the same narrative."""


# Per-scene keys the LOCK owns. Everything else on a recipe scene is recipe.
_LOCK_SCENE_FIELDS = ("title", "persona", "provenance", "narrative", "features")
# Spec-level keys the LOCK owns.
_LOCK_TOP_FIELDS = ("name", "narrative", "personas", "build_order")

_RECIPE_SUFFIX = ".recipe.yaml"
_LOCK_SUFFIX = ".narrative.lock.json"


def recipe_path(base_dir, slug: str) -> Path:
    return Path(base_dir) / f"{slug}{_RECIPE_SUFFIX}"


def lock_path(base_dir, slug: str) -> Path:
    return Path(base_dir) / f"{slug}{_LOCK_SUFFIX}"


def compose(recipe: dict, lock: dict) -> dict:
    """Join a recipe and a narrative lock into a raw spec dict. Pure.

    Scene ORDER comes from the lock: the story owns the sequence, the recipe
    only says how to film each beat. Every scene must exist on both sides — a
    mismatch is a loud error, never a silently empty recipe (which is the
    failure mode the pre-L1 merge had).
    """
    recipe_scenes = {
        (s.get("id") or "").strip(): s
        for s in (recipe.get("scenes") or [])
        if isinstance(s, dict)
    }
    lock_scenes = [s for s in (lock.get("scenes") or []) if isinstance(s, dict)]
    lock_ids = [(s.get("id") or "").strip() for s in lock_scenes]

    missing = [sid for sid in lock_ids if sid not in recipe_scenes]
    if missing:
        raise SpecCompositionError(
            f"narrative lock has scene(s) with no recipe: {', '.join(missing)}. "
            f"Add them to the recipe (id + show) or re-pull the narrative."
        )
    orphans = sorted(set(recipe_scenes) - set(lock_ids))
    if orphans:
        raise SpecCompositionError(
            f"recipe has scene(s) absent from the narrative: {', '.join(orphans)}. "
            f"The story owns the scene list — delete them locally or add the beat "
            f"on canopy-web."
        )

    scenes: list[dict] = []
    for ls in lock_scenes:
        sid = (ls.get("id") or "").strip()
        merged = dict(recipe_scenes[sid])
        merged.update({k: ls[k] for k in _LOCK_SCENE_FIELDS if k in ls})
        merged["id"] = sid
        scenes.append(merged)

    raw = {k: v for k, v in recipe.items() if k != "scenes"}
    raw.update({k: lock[k] for k in _LOCK_TOP_FIELDS if k in lock})
    raw["scenes"] = scenes
    return raw


def discarded_recipe_fields(recipe: dict, lock: dict) -> list[str]:
    """Recipe fields ``compose`` throws away, as human-readable lines. Pure.

    The merge is silent by design — the lock wins and nothing says so. That is
    fine when the recipe never carries story, and invisible when it does: 20
    ``narrative:`` blocks shipped into connect-labs recipes, every one
    discarded, and the render that was supposed to prove them measured no
    change and could not say why. Naming them costs nothing and is the only
    signal on the paths that skip ``check_locks`` — which, today, is all of
    them.
    """
    out: list[str] = []
    for f in _LOCK_TOP_FIELDS:
        if f in recipe and f in lock:
            out.append(f"top-level {f!r}")
    lock_scenes = {
        (s.get("id") or "").strip(): s
        for s in (lock.get("scenes") or [])
        if isinstance(s, dict)
    }
    for rs in recipe.get("scenes") or []:
        if not isinstance(rs, dict):
            continue
        sid = (rs.get("id") or "").strip()
        ls = lock_scenes.get(sid)
        if not ls:
            continue
        for f in _LOCK_SCENE_FIELDS:
            if f in rs and f in ls:
                out.append(f"scene {sid!r} {f!r}")
    return out


def load_spec_raw(path_or_slug, *, base_dir=None) -> dict:
    """Compose a spec to a raw dict, WITHOUT schema validation.

    Composition and validation are separate concerns. Several older walkthrough
    specs predate ``concept_claim`` being required and are not valid
    ``UnifiedSpec``s — the recorder has always filmed them as plain dicts, and
    gaining the two-file layout must not newly impose a schema on them. Callers
    that want the model call :func:`load_spec`.

    Accepts a bare slug (with ``base_dir``), a ``<slug>.recipe.yaml`` path, or a
    legacy unified ``<slug>.yaml`` path.
    """
    p = Path(path_or_slug)
    name = p.name

    if base_dir is not None and not name.endswith((".yaml", ".yml", ".json")):
        slug, directory = str(path_or_slug), Path(base_dir)
    elif name.endswith(_RECIPE_SUFFIX):
        slug, directory = name[: -len(_RECIPE_SUFFIX)], p.parent
    else:
        return yaml.safe_load(p.read_text()) or {}

    rpath, lpath = recipe_path(directory, slug), lock_path(directory, slug)
    if not lpath.exists():
        raise SpecCompositionError(
            f"no narrative lock at {lpath}. Run "
            f"`python -m scripts.ddd.narrative pull {slug}` to fetch the story "
            f"from canopy-web."
        )
    recipe = yaml.safe_load(rpath.read_text()) or {}
    lock = json.loads(lpath.read_text())
    discarded = discarded_recipe_fields(recipe, lock)
    if discarded:
        shown = ", ".join(discarded[:6])
        more = f" (+{len(discarded) - 6} more)" if len(discarded) > 6 else ""
        print(
            f"WARNING: {rpath.name} carries story the lock overwrites — {shown}{more}. "
            f"Editing it there changes nothing that renders. The story lives on "
            f"canopy-web: edit it, `python -m scripts.ddd.narrative pull {slug}`, "
            f"and delete the local copy.",
            file=sys.stderr,
        )
    return compose(recipe, lock)


def load_spec(path_or_slug, *, base_dir=None) -> UnifiedSpec:
    """Load and VALIDATE a spec, composing recipe + lock when that's the shape.

    The strict counterpart to :func:`load_spec_raw`. Use this wherever the old
    code called ``UnifiedSpec.model_validate`` on a spec file.
    """
    return UnifiedSpec.model_validate(load_spec_raw(path_or_slug, base_dir=base_dir))
